### PR TITLE
Bug fixed Multiple Sections selected 1.3.3 #259

### PR DESCRIPTION
**Pull request by tonilopezmr**
https://github.com/neokree/MaterialNavigationDrawer/issues/259

Bug solved

### CODE REVIEW

**Comment by Trojaner25** [comment]
Still not fixed:

!(not fixed)[http://puu.sh/hu8TD/fcc42d3be4.png]

**Comment by tonilopezmr** [comment]
You use my fork?

**Comment by Trojaner25** [comment]
Yes

**Comment by tonilopezmr** [comment]
But your problem not is the same, those sections not belong to different lists (sectionList and bottomSectionList), if your project is on github show me your code!

Other users have no any problem and I tested the function.

**Comment by Trojaner25** [comment]
I have a group at the bottom too, it also happens there.

I already moved to another Material Drawer Lib, since this one isnt maintained anymore...

**Pull request closed without merging**
