### PR TITLE
Added more customization

### PR DESCRIPTION
**Pull request by qgadrian**
I added color customization  to drawer. Also, now user drawer background may be a color instead necessarily a bitmap.

Finally fixed a bug where the action bar where the action bar color misses the correct one for the default fragment.

### CODE REVIEW

**Comment by neokree** [comment]
Color customization is added to the 1.3 alpha, committed just now. 

What do you mean with:
*Finally fixed a bug where the action bar where the action bar color misses the correct one for the default fragment.* ?

**Comment by qgadrian** [comment]
Commit [51aa1ae](https://github.com/qgadrian/MaterialNavigationDrawer/commit/51aa1aed2394ee9714e674f44bcf7ad8aeb4db14) fixes a bug where if you provide a color to the first section, action bar will be default color until you change the current section.

**Comment by neokree** [comment]
Oh, thank you for finding this bug, I will update the library. Sorry But with the last commit I can't simply merge your code to the library, but your help is appreciated.

With the 1.3 alpha you can set the drawer color in your custom Theme using this item:
```xml
        <item name="drawerColor">#fafafa</item>
```

**Comment by qgadrian** [comment]
Nice. I'll close the pull request then.

Glad to help.

**Pull request closed without merging**
