### PR TITLE
Update colors to material 

### PR DESCRIPTION
**Pull request by athingunique**
Update themed drawer background colors to material values.
Update divisor color to be more neutral on both light and dark backgrounds.

### CODE REVIEW

**Comment by mrcasals** [comment]
Can you add a screenshot of the result? :)

**Comment by neokree** [comment]
good work!

**Comment by athingunique** [comment]
@neokree It seemed to work, but I'm not sure that I changed the divisor color everywhere that it is referenced. Could you make sure?

**Comment by neokree** [comment]
certanly

**Pull request merged**
